単体テスト用コード作成（第一稿）
al22-1B-01/meal_shield pull request #32
Opened 2024-06-22 12:36 UTC by xEuphemia

単体テスト用コードレビューのためのPR

2024-06-22 13:37 UTC, iamtatsuki05 requested changes
このブランチはdevelopの修正が取り込まれていなそうなので取り込みをした後で修正してください。
https://qiita.com/jefftech/items/aa9c2879c6e35587df07

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_embedding.py
> +            'recipe_score': 0.0,
imo:
ranking関数に渡しているときは'recipe_score'を渡していないのでいらない

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_embedding.py
> +    result = scoring_embedding(allergies, recipes)
imo:
テストのパターン網羅のためにOptionalの引数があるときとないときで検証した方が良い。
https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking_embedding.py#L91C5-L91C17

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_count.py
> +    result = scoring_count(allergies, recipes)
imo:
テストのパターン網羅のためにOptionalの引数があるときとないときで検証した方が良い。
https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking_count.py#L73

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_count.py
> +            'recipe_score': 0.0,
imo:
ranking関数に渡しているときは'recipe_score'を渡していないのでいらない

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_chatgpt.py
> +            'recipe_score': 0.0,
imo:
ranking関数に渡しているときは'recipe_score'を渡していないのでいらない

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_chatgpt.py
> +    result = scoring_chatgpt(allergies, recipes)
imo:
テストのパターン網羅のためにOptionalの引数があるときとないときで検証した方が良い。
https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking_chatgpt.py#L78

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_embedding.py
want:
他の関数の単体テストも実施した方が良い
- https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking_embedding.py#L35

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_embedding.py
imo:
test_scoring_embeddingのテストケースを増やしてもらう必要があるので使いまわすallergies, recipes辺りはグローバルに定義して良さそう

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_count.py
want:
他の関数も単体テストしてください。
- https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking_count.py#L44
- https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking_count.py#L55

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_count.py
imo:
test_scoring_countのテストケースを増やしてもらう必要があるので使いまわすallergies, recipes辺りはグローバルに定義して良さそう

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking_chatgpt.py
imo:
test_scoring_chatgptのテストケースを増やしてもらう必要があるので使いまわすallergies, recipes辺りはグローバルに定義して良さそう

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking.py
want:
他の関数のテストケースも単体テストを実装してください。
- https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking.py#L12
- https://github.com/al22-1B-01/meal_shield/blob/feature/test_ranking/backend/src/meal_shield/ranking/ranking.py#L24

2024-06-22 13:37 UTC, iamtatsuki05 commented on backend/tests/meal_shield/ranking/test_ranking.py
imo:
test_ranking_recipeで使いまわすallergies, recipes辺りはグローバルに定義して良さそう

2024-06-28 14:42 UTC, xEuphemia commented
test_ranking_count.pyでscore_recipe関数がimportできないという理由でテストがブロックされているようなのですが、原因がわかりません。
docker内でのpoetry run pytest test_ranking_count.pyでは正常に実行でき、単体テストそのものは動作しています。
また、push前にすべてのファイルに対してblackとisortを実行しています。

2024-06-28 16:07 UTC, iamtatsuki05 requested changes
developのコードを反映させてください。

2024-06-29 09:24 UTC, iamtatsuki05 approved these changes

2024-06-29 09:25 UTC, merged