Pull Request practice Kengo Kobayashi.
al22-1B-01/meal_shield pull request #4
Opened 2024-05-19 06:56 UTC by xEuphemia

Pull Request practice Kengo Kobayashi.

2024-05-19 14:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
コメントテスト

2024-06-04 05:10 UTC, iamtatsuki05 requested changes

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +from typing import List, Dict, Union
nits:
List, Dictはpython3.9以降だとtypingからimportせずに小文字でそのまま扱う

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +recipes = [
nits:
グローバル変数は大文字

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +print(excluded_recipes_list)
imo:
printは使わずにlogging, loggerを使う

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +def get_embeddings(texts, model_name="text-embedding-ada-002"):
ここ参考にする
https://weel.co.jp/media/tech/text-embedding-3/

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +def score_allergens(recipes, allergens, model_name="text-embedding-ada-002"):
nits:
出力の型が無い

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +recipes = [
nits:
グローバル変数は大文字

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +        "recipe_ingredients": ["ミルク", "卵", "小麦粉"],
nits:
ダブルコーテーションではなく、シングル

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +print(scores)
imo:
loggerを使う

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +def sort_recipes_by_allergy_score(scores):
出力の型が無い

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +scores = {
nits:
グローバル変数は大文字

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +print(sorted_recipes)
imo:
loggerを使う

2024-06-04 05:10 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +def main():
ask:
main関数と各関数の外で実行している関数、printの違いは？

2024-06-04 06:21 UTC, iamtatsuki05 requested changes

2024-06-04 06:21 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +from logging import getLogger       # add (0.1->0.2): loggingパッケージのimport
imo:
こんな感じで書く
```python
import logging
from multiprocessing import Pool
...
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

```

2024-06-04 06:21 UTC, iamtatsuki05 commented on backend/src/ranking.py
nits:
importとかが諸々おかしそうなのでlintをする。

2024-06-04 06:21 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +    sorted_recipes = sort_recipes_by_allergy_score(scores)
nits:
ranking_recipi関数にまとめる（内部設計書）

2024-06-04 07:22 UTC, iamtatsuki05 commented on backend/src/ranking.py
> +def get_embeddings(texts, model_name="text-embedding-ada-002"):
APIキー発行
https://www.ai-souken.com/article/how-to-get-chatgpt-api-key

2024-06-11 05:09 UTC, iamtatsuki05 reviewed
完成したときに再度アサインしてください。
（通知回避用）

2024-06-11 07:31 UTC, iamtatsuki05 requested changes

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +def check_allergens_with_chatgpt(ingredients, allergens):
nits:
型が無い

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    recipes, allergens, model_name='text-embedding-3-small'
nits:
型が無い

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +        engine="davinci",
nits:
modelは`davinci`ではなく`gpt-3.5-turbo`を使います。
modelの動作コードは下記を参考にしてください。
https://okumuralab.org/~okumura/python/chatgpt_api.html#:~:text=res%20%3D%20client.chat.completions.create(%0A%20%20%20%20model%3D%22gpt%2D3.5%2Dturbo%22%2C%0A%20%20%20%20messages%3D%5B%0A%20%20%20%20%20%20%20%20%7B%22role%22%3A%20%22system%22%2C%20%22content%22%3A%20%22%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AF%E8%B3%A2%E3%81%84AI%E3%81%A7%E3%81%99%E3%80%82%22%7D%2C%20%20%23%20%E5%BD%B9%E5%89%B2%E8%A8%AD%E5%AE%9A%EF%BC%88%E7%9C%81%E7%95%A5%E5%8F%AF%EF%BC%89%0A%20%20%20%20%20%20%20%20%7B%22role%22%3A%20%22user%22%2C%20%22content%22%3A%20%221%E3%81%9F%E3%81%991%E3%81%AF%EF%BC%9F%22%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20%E6%9C%80%E5%88%9D%E3%81%AE%E8%B3%AA%E5%95%8F%0A%20%20%20%20%5D%2C%0A%20%20%20%20temperature%3D1%20%20%23%20%E6%B8%A9%E5%BA%A6%EF%BC%880%2D2%2C%20%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%881%EF%BC%89%0A)

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    prompt = f"次の材料リストにアレルギー品目が含まれているかどうかを教えてください:\n\n材料: {', '.join(ingredients)}\nアレルギー品目: {', '.join(allergens)}\n\nアレルギー品目が含まれている材料をリストアップし、その数を返してください。"
nits:
プロンプトでの結果具体的に数字になるように数字の幅、出力形式を決めましょう。

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    return response.choices[0].text.strip()
nits:
このままだと出力の型が文字列になっています。
プロンプトで出力のフォーマットを指定して、正規表現で抽出、抽出した数字をpythonのfloat or int型変換するようにしてください。

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +        allergen_count = len(result.split())
imo
↑の`result`では数字が返ってくるようにして結果の格納だけをするようにすれば良い。（resultではなくscoreという名前にした方が良い）

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +def check_allergens_with_chatgpt(ingredients, allergens):
imo:
checkするのではなくスコアリングを指せるので、calc_allergens_include_scoreのように関数名を明確化させる。

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking.py
> +) -> (list[str], list[dict[str, Union[str, list[str]]]]):
nits:
出力の型で丸括弧は不自然

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking.py
> +) -> (list[str], list[dict[str, Union[str, list[str]]]]):
nits:
出力の型で丸括弧は不自然

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +) -> dict[str, list[float]]:
nits:
この関数の返り値は複数のはずなので型がおかしい。

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    return recipe
nits:
for文の一番最後のデータしか返していない
`recipes`のはず

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_count.py
> +    return result
nits:
for文の一番最後のデータしか返していない

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_count.py
> +        result[recipe_title] = allergen_counts
ask:
タイトルをなぜカウントした回数に上書きしている？

recipeにscoreとして格納するはずでは？

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    response = openai.Embedding.create(
imo:
`client.embeddings.create`を使う気がします。
https://dev.classmethod.jp/articles/openai-api-update-2024-01/#:~:text=Python%E3%82%B3%E3%83%BC%E3%83%89%E3%81%A8%E3%81%97%E3%81%A6%E3%81%AF%E4%BB%A5%E4%B8%8B%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB%E4%BD%BF%E3%81%84%E3%81%BE%E3%81%99%E3%80%82

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    allergen_embeddings = [get_embedding(allergen) for allergen in allergens]
imo:
食材、アレルギーごとにembeddingを作るのではなく、chatgpt同様に`.join`を使って1つのテキストにすれば良いと思います。

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    return np.mean(scores)
↑の変更をするとcos類似度の計算は1度で済むので平均を取ったりfor文を実行する必要はない。

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +def calculate_allergen_score(recipe, allergens):
nits:
型が無い。

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    recipes, allergens, model_name='text-embedding-3-small'
nits:
型が無い

2024-06-11 07:31 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    return recipe
nits:
for文の一番最後のデータしか返していない

2024-06-13 00:32 UTC, xEuphemia commented
前回のPRでコメントをいただいた部分を修正しました。
TODOについては最上部に記載してあります。
一度コード部分を確認していただきたいです。よろしくお願いします。

2024-06-13 01:18 UTC, iamtatsuki05 requested changes

2024-06-13 01:18 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +def calc_allergens_include_score(
imo:
- embeddingのところと同じ名前を使っていてわかりにくい
- 何を使っての算出かわからない

それぞれ名前を適切に設定するか`_`を関数名の一番最初につけて明示的にこのファイルでしか使わないことがわかるようにしてください。

2024-06-13 01:18 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_count.py
> +def extract_allergy_words(
imo:
- embeddingのところと同じ名前を使っていてわかりにくい
- 何を使っての算出かわからない

それぞれ名前を適切に設定するか`_`を関数名の一番最初につけて明示的にこのファイルでしか使わないことがわかるようにしてください。

2024-06-13 01:18 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    for recipe in excluded_recipes_list:
imo:
処理時間がかかりそうなので`tqdm`でラップして処理回数、時間がわかるようにしてください。

2024-06-13 01:18 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    for recipe in excluded_recipes_list:
imo:
処理時間がかかりそうなので`tqdm`でラップして処理回数、時間がわかるようにしてください。

2024-06-13 01:18 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +load_dotenv()
nits:
`env.py`でやっているので不要

2024-06-13 01:18 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_count.py
> +    scored_recipes_list = [{}]
nits:
使っていなそう？
これをしたいなら`defaltdict`で良さそう

2024-06-13 01:18 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    allergen_embeddings = get_embedding(''.join(allergies_list))
nits:
ベースの関数は単体を返しているので複数形じゃない

2024-06-16 03:41 UTC, iamtatsuki05 requested changes

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    # NOTE: デバッグ用info
nits:
デバックはlogger.debugにしないと運用時に毎回コンソールに出力される。
（消すかログレベルを変更）

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    m = re.match(r'score=(\d+)', res)
nits:
パターンをグローバルに定義してコンパイルした方が実行速度が早い

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +logger.info('ranking_chatgpt.py was imported!')
nits:
デバックはlogger.debugにしないと運用時に毎回コンソールに出力される。
（消すかログレベルを変更）

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    return float(score)
imo:
try catch形式で実装しておかないと、キャストができないと処理が落ちる

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_count.py
> +logger.info('ranking_count.py was imported!')
nits:
デバックはlogger.debugにしないと運用時に毎回コンソールに出力される。
（消すかログレベルを変更）

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +logger.info('ranking_embedding.py was imported!')
nits:
デバックはlogger.debugにしないと運用時に毎回コンソールに出力される。
（消すかログレベルを変更）

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +        # dimensions = 2
nits:
不要なオプションは削除

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_embedding.py
> +    allergen_embedding = get_embedding(''.join(allergies_list))
imo:
joinの時にカンマかスペースを入れないとすべてが結合された文字列になるので精度がかなり下がりそう

2024-06-16 03:41 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +    organized_prompt = prompt.format(allergies_list, ingredient)
imo:
allergies_list, ingredientはlistなのでembeddingどうように joinで結合して上げた方が精度が良さそう

2024-06-17 03:35 UTC, iamtatsuki05 requested changes

2024-06-17 03:35 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking.py
> +def main():
want:
testコードにする

2024-06-17 03:35 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +PATTERN = r'score=(\d+)'
nits:
速度に影響するのでコンパイルする

2024-06-17 03:35 UTC, iamtatsuki05 commented on backend/src/meal_shield/ranking/ranking_chatgpt.py
> +        logger.info(e)
imo:
エラーだけ返すと後段の処理でエラーになるので適当にスコアの最低値がくるようにしてあげると良さそう

2024-06-18 05:08 UTC, iamtatsuki05 approved these changes

2024-06-18 05:09 UTC, merged