Pull request practice by Okii
al22-1B-01/meal_shield pull request #5
Opened 2024-05-19 12:20 UTC by okiijin

# WHY
プルリクエストの練習のため
# WHAT
・未完成のプログラムファイルの追加

2024-05-19 12:30 UTC, okiijin commented
@iamtatsuki05

2024-05-19 14:13 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
imo:
関数の単位が増えそうなのでスクレイピング用にディレクトリを切って良さそう
`backend/src/meal_shield/scrap/`

2024-05-19 14:13 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
> +import chromedriver_binary
nits: 
リンターを動かしてなさそう
ref:
https://zenn.dev/tanny/articles/cdb555d6124a2a

2024-06-04 05:01 UTC, iamtatsuki05 requested changes

2024-06-04 05:01 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
> +from typing import List
nits:
python3.9以降だとtypingからListを読み込まないでlistをそのまま使う

2024-06-04 05:01 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
> +def scraping_and_excluding(allergy_list, recipe_name: str):
nits:
出力の型が無い

2024-06-04 05:01 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
> +def excluding(allergy_list: List[str], recipe_data_list: List[dict]):
nits:
出力の型が無い

2024-06-04 05:02 UTC, iamtatsuki05 commented
@okiijin 
mainの実行結果を適当にコメントに貼って欲しいです。

2024-06-04 05:04 UTC, iamtatsuki05 requested changes

2024-06-04 05:04 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
> +from scrape import cookpad
imo:
多分importミスってる
```python
from meal_shield.scrape.cookpad import hoge
```

2024-06-04 05:26 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +from concurrent.futures import ThreadPoolExecutor
https://qiita.com/XPT60/items/61f124cdc7979f4d63b2

2024-06-04 06:31 UTC, okiijin commented
mainの実行結果の一部です

ひよこ豆のココナッツカレー
['にんにく', '玉ねぎ', 'マッシュルーム', '赤パプリカ', 'ココナッツオイル', 'ひよこ豆', '塩', '✩クミン', '✩シナモン', '✩コリアンダー', '✩ターメリック', 'トマト缶', 'ココナッツミルク', '塩胡椒', 'チリ', 'ガラムマサラ']
https://cookpad.com/recipe/6596794
https://img.cpcdn.com/recipes/6596794/894x1461s/f60abaea7bc1330f957f07e91cc110e9?u=16507498&p=1610216874

ココナッツキーマカレー
['玉ねぎ', '合い挽き肉', 'ピーマン', 'トマト', 'コリアンダー', 'クミン', 'ターメリック', 'ココナッツミルク', 'レモン汁', '塩', 'サラダ油', 'にんにく(チューブでも可)', 'しょうが(チューブでも可)']
https://cookpad.com/recipe/6569160
https://img.cpcdn.com/recipes/6569160/894x1461s/70bdf5894bda05dceecdc4999c55ace2?u=9622158&p=1608198807

南瓜と海老のココナッツカレー
['ニンニク', '生姜', '油', 'オニオンソテー', 'カットトマト缶', '☆コリアンダー、クミン、ターメリック、塩', '冷凍南瓜', '冷凍えび', 'ココナッツミル ク', '水']
https://cookpad.com/recipe/6555878
https://img.cpcdn.com/recipes/6555878/894x1461s/16305ec1f2a6e6c2ba4c8b203cef1b90?u=4236857&p=1607252901

ココナッツ鯖ドライトマトカレー
['ドライトマト', 'オリーブオイル', 'マギーブイヨン', '鯖水煮缶', 'ココナ ッツミルク缶', 'カレー粉', '水']
https://cookpad.com/recipe/6547575
https://img.cpcdn.com/recipes/6547575/894x1461s/6b542fe6432cc76083390cca1643d79f?u=25315276&p=1606642530

スリランカ風魚の頭のココナッツ汁カレー
['魚の頭(今回はカジキを使用)', 'ニンニク', '生姜', '紫玉ねぎ', 'トマト', '青唐辛子', '塩、胡椒', 'ココナッツミルク', 'カレーリーフ', 'パンダンリーフ', 'ゴラカ(梅干し代用可)', 'ターメリック', 'チリパウダー', 'カレーパウ ダー', 'シナモンスティック']
https://cookpad.com/recipe/6508512
https://img.cpcdn.com/recipes/6508512/894x1461s/3d5f093361ad5be8d72fe0b0f2dc95bf?u=369603&p=1603946138

ココナッツシーフードカレー
['えび', 'ほたて', 'オクラ', '玉ねぎ', 'ニンニク', 'しょうが', 'トマト水 煮缶', 'ブイヨン（あればフュメドポワソン）', 'ココナッツミルク', 'パプリ カパウダー', 'チリペッパー', 'ターメリック', 'ガラムマサラ', '白ワイン', '塩', 'コショウ', 'オリーブオイル', 'ごはん']
https://cookpad.com/recipe/7277806
https://img.cpcdn.com/recipes/7277806/894x1461s/390a5e636d7116d2c24b035190919cf2?u=39152&p=1659941082

検索結果59件
検索レシピ名:ココナッツカレー
除外品目:
['鶏', 'とり']

2024-06-04 06:43 UTC, iamtatsuki05 requested changes

2024-06-04 06:43 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +limit_page = 10
nits:
大文字

2024-06-04 06:43 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +
nits:
ココの改行は不要

2024-06-04 06:43 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +    with Pool(num_cpu) as pool_2:
imo:
前段のpoolは終了しているのでpool_nの形にしないで良い

2024-06-04 06:43 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +
imo:
改行が不自然

2024-06-04 06:43 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +def make_url_list(recipe_name: str) -> list[str]:
nits:
Noneが出力され可能性があるので
Optional[list[str]]

2024-06-04 06:43 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +def scraping_cookpad(recipe_name: str) -> list[dict]:
nits:
-  Naneが出力される可能性があるのでOptional[list[dict]]
- dictの中身まで書く

2024-06-04 07:45 UTC, iamtatsuki05 requested changes

2024-06-04 07:45 UTC, iamtatsuki05 commented on backend/src/meal_shield/scrape/cookpad.py
> +        sum_of_pages = int(page_parts[1].replace(",", ""))
nits:
ダブルコーテーションじゃなくてシングルコーテーション

2024-06-04 07:45 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
> +            print(f"{recipe_data['recipe_img_url']}\n")
nits:
- printを使わずにloggerを使う
- ダブルコーテーションを使わない

2024-06-08 06:09 UTC, iamtatsuki05 requested changes

2024-06-08 06:09 UTC, iamtatsuki05 commented on backend/src/app.py
> +from meal_shield.backend.src import ranking, scraping_and_excluding
nits:
ミスってる
```python
from meal_shield.scrape.scraping_and_excluding import scraping_and_exclude
```

2024-06-08 06:09 UTC, iamtatsuki05 commented on backend/src/meal_shield/app.py
このファイルいらないので削除してください。

2024-06-08 06:09 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
> +    logger = logging.getLogger(__name__)
imo:
main関数の外で実行する

2024-06-08 06:09 UTC, iamtatsuki05 commented on backend/src/meal_shield/scraping_and_excluding.py
imo:
ファイル構成がわかりにくいので機能ごとにディレクトリに移したいです。
`meal_shield/backend/src/meal_shield/scrape/scraping_and_excluding.py`に移してください。

2024-06-11 05:06 UTC, iamtatsuki05 approved these changes

2024-06-11 05:06 UTC, iamtatsuki05 commented on backend/src/app.py
> +from meal_shield.backend.src import ranking
imo:
このブランチにはこの関数はまだ存在しないので今はとりあえず、コメントアウトして良さそう

2024-06-11 05:06 UTC, merged